default cart page created
The-Donovans-Venom-501c3/the-donovans-piano-room pull request #88
Opened 2024-07-24 18:36 UTC by KavinKarthik-git

Default cart page created in '/cart' link

2024-07-25 01:10 UTC, aouiniamine requested changes
You have redundant BookItem.tsx you should delete the first one in the app/bookstore/[id]/components/BookItem.tsx
The frequently used component is already setup in src/app/bookstore/[id]/components/FrequentlyPurchasedTogether.tsx
move it to src/components/atom/books/ and there too the BookItem.tsx file

2024-07-25 21:50 UTC, aouiniamine commented
It would be best if you fixed the padding at the bottom of this component.
![image](https://github.com/user-attachments/assets/fe57b85c-4baf-4aed-b73e-50f7cc8cb583)

2024-07-26 04:14 UTC, KavinKarthik-git commented
Removed redundant BookItem.tsx  and moved FrequentlyPurchasedTogether.tsx to src/components/atom/
And fixed the padding as mentioned

2024-07-26 18:52 UTC, aouiniamine approved these changes

2024-07-26 18:53 UTC, merged